/* mmdr.h — C ABI for mermaid-ffi. GENERATED by cbindgen; DO NOT EDIT. */

#ifndef MMDR_H
#define MMDR_H

/* WARNING: generated by cbindgen — edits are overwritten. Regenerate via cbindgen.toml. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Default DoS source-size cap: 256 KB (PRD §4.3 DoS item 1). Used when
// `MmdrOptions.max_source_bytes == 0`.
#define DEFAULT_MAX_SOURCE_BYTES 262144

// Default DoS node cap: 5000 nodes (PRD §4.3 DoS item 2) — the TRUE compute
// bound (enforced pre-layout). Used when `MmdrOptions.max_nodes == 0`.
#define DEFAULT_MAX_NODES 5000

// `color_override_mask` bit: background slot.
#define MASK_BACKGROUND 1

// `color_override_mask` bit: foreground (text + line) slot.
#define MASK_FOREGROUND 2

// `color_override_mask` bit: accent (primary) slot.
#define MASK_ACCENT 4

// Current ABI version. Bumped to `2` for v0.6 to reflect the additive second
// render entry point (`mmdr_render_png`); the bump is purely additive — the
// `MmdrResult`/`MmdrOptions` byte layouts are byte-identical to v0.5, so a v0.5
// caller that only uses `mmdr_render_svg` keeps working (see the version-check
// operator in [`crate::abi`]).
#define MMDR_ABI_VERSION 2

// C status code returned in [`crate::types::MmdrResult::status`] (as `i32`).
typedef enum {
  // Render succeeded; `data_ptr`/`data_len` carry the payload.
  MmdrStatus_Ok = 0,
  // `ParseError::UnexpectedToken` — also the generic parser-error fallback.
  MmdrStatus_ErrUnexpectedToken = 1,
  // `ParseError::UnknownParticipant`.
  MmdrStatus_ErrUnknownParticipant = 2,
  // `ParseError::UnclosedSubgraph`.
  MmdrStatus_ErrUnclosedSubgraph = 3,
  // `ParseError::InvalidDirective`.
  MmdrStatus_ErrInvalidDirective = 4,
  // Diagram type not in the FFI-wrapper MVP allowlist (PRIMARY gate, Phase
  // 3). Set BEFORE the renderer runs — the lenient parser is never invoked.
  MmdrStatus_ErrUnsupported = 5,
  // FFI-only guard: input bytes were not valid UTF-8. Never produced by the
  // renderer.
  MmdrStatus_ErrInvalidUtf8 = 6,
  // FFI-only guard: a null pointer was passed where a non-null one is
  // required. Never produced by the renderer.
  MmdrStatus_ErrNullArg = 7,
  // `opts.struct_size` / `opts.abi_version` disagree with the binary
  // (forward-compat guard).
  MmdrStatus_ErrVersionMismatch = 8,
  // A DoS bound tripped (source-size or node cap).
  MmdrStatus_ErrTooLarge = 9,
  // RESERVED for a future pure-Rust internal deadline (§13-D10). NOT emitted
  // by the wrapper in MVP; the MVP timeout is Swift-side perceived-latency
  // only. Kept so wiring it later needs no ABI bump.
  MmdrStatus_ErrTimeout = 10,
  // `catch_unwind` tripped — an internal renderer bug, NOT user input. The
  // payload is redacted to a fixed sentinel (no internal paths leak).
  MmdrStatus_ErrPanic = 99,
} MmdrStatus;

// Transparent, versioned render result. Layout is part of the public ABI
// (additive only). Total size = **40 bytes**, alignment = 8, no internal
// padding (4-byte block precedes the 8-byte block).
typedef struct {
  // `== MMDR_ABI_VERSION`; lets Swift assert header/binary agreement.
  uint32_t abi_version;
  // `== size_of::<MmdrResult>()` at build; forward-compat guard.
  uint32_t struct_size;
  // [`crate::status::MmdrStatus`] as `i32`.
  int32_t status;
  // 1-based line; valid only when `loc_valid != 0`. `0` = column/line not
  // reported for this error shape.
  uint32_t err_line;
  // 1-based column; valid only when `loc_valid != 0`. `0` = column not
  // reported (e.g. line-only errors).
  uint32_t err_col;
  // `0` = `err_line`/`err_col` are unknown/unpopulated; nonzero = at least
  // `err_line` is accurate (replaces overloading `(1,1)` as a sentinel).
  uint32_t loc_valid;
  // Payload byte length, no NUL terminator. FIXED-WIDTH `u64` (NOT `usize`)
  // so the ABI is pointer-width-independent.
  uint64_t data_len;
  // FORMAT-DEPENDENT payload (v7-MF5): UTF-8 SVG bytes (`mmdr_render_svg`,
  // status Ok) / raw BINARY PNG bytes (`mmdr_render_png`, status Ok) /
  // UTF-8 (redacted) error-message bytes (any status != Ok); may be null.
  // NOTE: PNG bytes are binary, NOT UTF-8 — a Swift consumer MUST wrap them
  // in `Data` for `UIImage`/`NSImage`, never `String(bytes:encoding:.utf8)`
  // (which returns nil).
  uint8_t *data_ptr;
} MmdrResult;

// Forward-compatible POD options. Total size = **56 bytes**, alignment = 4, no
// padding (every field is 4-byte). `abi_version` precedes `struct_size`,
// IDENTICAL to `MmdrResult`'s guard-field order.
typedef struct {
  // `== MMDR_ABI_VERSION` (FIRST, matching `MmdrResult`'s guard order).
  uint32_t abi_version;
  // Caller sets `size_of::<MmdrOptions>()`; Rust validates exactly.
  uint32_t struct_size;
  // Starting palette: `0` = modern, `1` = mermaid_default (additive).
  int32_t base_theme;
  // bit0 = background set, bit1 = foreground set, bit2 = accent set. A `0`
  // bit => use `base_theme` for that slot (NOT an alpha sentinel). Bits 3–31
  // RESERVED, MUST be zero; the wrapper IGNORES unrecognized high bits
  // (forward-compat — no `ErrVersionMismatch` on a set reserved bit).
  uint32_t color_override_mask;
  // `0xRRGGBBAA`; applied verbatim iff `(mask & 0b001)`. `0x00000000`
  // (`Color.clear`) is a LEGAL value when its bit is set.
  uint32_t background_rgba;
  // Text/line color; applied iff `(mask & 0b010)`.
  uint32_t foreground_rgba;
  // Primary/accent; applied iff `(mask & 0b100)`.
  uint32_t accent_rgba;
  // `<= 0` => default.
  float node_spacing;
  // `<= 0` => default.
  float rank_spacing;
  // `0` => unset.
  float preferred_aspect_w;
  // `0` => unset.
  float preferred_aspect_h;
  // DoS source-size cap; `0` => wrapper default (262144).
  uint32_t max_source_bytes;
  // DoS node cap; `0` => wrapper default (5000).
  uint32_t max_nodes;
  // ACCEPTED but IGNORED by the Rust wrapper in MVP — carries the Swift
  // adapter's perceived-latency deadline for symmetry/forward-compat; the
  // wrapper does NOT enforce a pure-Rust deadline in MVP. `0` => default.
  uint32_t timeout_ms;
} MmdrOptions;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Render Mermaid source to **vector SVG** (`data_ptr` = UTF-8 SVG bytes).
// `opts_ptr` may be null (defaults). Returns an owned handle freed with
// `mmdr_result_free`; returns null only on allocation failure.
//
// # Safety
// `src_ptr` must be null or valid for `src_len` bytes; `opts_ptr` must be null
// or point to a valid [`MmdrOptions`].
MmdrResult *mmdr_render_svg(const uint8_t *src_ptr, size_t src_len, const MmdrOptions *opts_ptr);

// Render Mermaid source to **raster PNG** (`data_ptr` = binary PNG bytes —
// wrap in `Data`, NEVER decode as UTF-8). Same ownership / status / panic
// contract as `mmdr_render_svg`. The rasterization runs with an egress-locked,
// zero-filesystem `usvg::Options` (PRD §4.7b) and is INSIDE the `catch_unwind`.
//
// # Safety
// `src_ptr` must be null or valid for `src_len` bytes; `opts_ptr` must be null
// or point to a valid [`MmdrOptions`].
MmdrResult *mmdr_render_png(const uint8_t *src_ptr, size_t src_len, const MmdrOptions *opts_ptr);

// Free a result. No-op on null. The **only** correct deallocator (PRD
// Arbitration E). Reconstitutes the `Box<[u8]>` payload (null-guarded) and the
// `Box<MmdrResult>`, dropping both.
//
// # Safety
// `res` must be null or a pointer returned by `mmdr_render_svg`/`_png` that has
// not already been freed.
void mmdr_result_free(MmdrResult *res);

// Payload pointer accessor (fields are also directly readable — transparent
// ABI). Null on a null `res`.
//
// # Safety
// `res` must be null or a valid `MmdrResult` pointer.
const uint8_t *mmdr_result_data(const MmdrResult *res);

// Payload length accessor (bytes). `0` on a null `res`.
//
// # Safety
// `res` must be null or a valid `MmdrResult` pointer.
uint64_t mmdr_result_len(const MmdrResult *res);

// Status accessor. `ErrNullArg` (7) on a null `res`.
//
// # Safety
// `res` must be null or a valid `MmdrResult` pointer.
int32_t mmdr_result_status(const MmdrResult *res);

// `err_line` accessor. `0` on a null `res`.
//
// # Safety
// `res` must be null or a valid `MmdrResult` pointer.
uint32_t mmdr_result_err_line(const MmdrResult *res);

// `err_col` accessor. `0` on a null `res`.
//
// # Safety
// `res` must be null or a valid `MmdrResult` pointer.
uint32_t mmdr_result_err_col(const MmdrResult *res);

// `loc_valid` accessor. `0` on a null `res`.
//
// # Safety
// `res` must be null or a valid `MmdrResult` pointer.
uint32_t mmdr_result_loc_valid(const MmdrResult *res);

// A `'static`, NUL-terminated version string. Never freed.
const char *mmdr_version(void);

// No-op latency hint (PRD Arbitration A). The embedded font is seeded into its
// `OnceLock` database at construction with ZERO filesystem I/O, so the first
// render is correct with no prior init. This call merely forces the font
// `OnceLock`s to evaluate early (off the render hot path). Idempotent,
// thread-safe, and panic-isolated; guarantees nothing about correctness.
void mmdr_init(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MMDR_H */
